<?php
//
// Database "locations"
//

// locations.placement
$placement = array(
	// Local testing here:
	// array("ID"=>5852,"Area"=>"Expo Hall","Subarea"=>"Expo West")

	// Here we go!
  array("ID"=>43737,"Area"=>"Zone 4","Subarea"=>"3D Hubs"),
  array("ID"=>43738,"Area"=>"Zone 4","Subarea"=>"3D Maker World"),
  array("ID"=>34871,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>34895,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>34946,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>35221,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>35301,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>35323,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>35811,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36065,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36079,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36144,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36320,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36440,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36515,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36519,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36524,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36552,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36697,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36835,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36873,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>36878,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>37083,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>37254,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>37258,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>37456,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>37547,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>37641,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>37861,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>37867,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>38129,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>38131,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>38158,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>38161,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>38185,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>38216,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>38287,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>38724,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>38781,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>38794,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>39060,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>39069,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>39086,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>39816,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>39905,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>40393,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>40429,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>40639,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>40828,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>41107,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>41847,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>42753,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>43096,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>43280,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>45086,"Area"=>"Zone 2","Subarea"=>"3D Printer Village"),
  array("ID"=>43739,"Area"=>"Zone 4","Subarea"=>"3DP4E"),
  array("ID"=>37413,"Area"=>"Zone 5","Subarea"=>"Activities"),
  array("ID"=>38063,"Area"=>"Zone 5","Subarea"=>"Activities"),
  array("ID"=>38863,"Area"=>"Zone 5","Subarea"=>"Activities"),
  array("ID"=>39472,"Area"=>"Zone 5","Subarea"=>"Activities"),
  array("ID"=>40530,"Area"=>"Zone 5","Subarea"=>"Activities"),
  array("ID"=>40718,"Area"=>"Zone 5","Subarea"=>"Activities"),
  array("ID"=>40959,"Area"=>"Zone 5","Subarea"=>"Activities"),
  array("ID"=>42571,"Area"=>"Zone 5","Subarea"=>"Activities"),
  array("ID"=>35625,"Area"=>"Zone 4","Subarea"=>"Activity Row"),
  array("ID"=>36372,"Area"=>"Zone 4","Subarea"=>"Activity Row"),
  array("ID"=>37220,"Area"=>"Zone 4","Subarea"=>"Activity Row"),
  array("ID"=>41200,"Area"=>"Zone 4","Subarea"=>"Activity Row"),
  array("ID"=>41563,"Area"=>"Zone 4","Subarea"=>"Activity Row"),
  array("ID"=>43110,"Area"=>"Zone 4","Subarea"=>"Activity Row"),
  array("ID"=>43267,"Area"=>"Zone 4","Subarea"=>"Activity Row"),
  array("ID"=>43740,"Area"=>"Zone 2","Subarea"=>"Afinia 3D"),
  array("ID"=>44512,"Area"=>"Zone 4","Subarea"=>"AGIC"),
  array("ID"=>43741,"Area"=>"Zone 4","Subarea"=>"AIO Robotics"),
  array("ID"=>44499,"Area"=>"Zone 2","Subarea"=>"Aleph Objects"),
  array("ID"=>44497,"Area"=>"Zone 3","Subarea"=>"Altium"),
  array("ID"=>43742,"Area"=>"Zone 3","Subarea"=>"ANNIKKEN PTE LTD"),
  array("ID"=>44500,"Area"=>"Zone 3","Subarea"=>"Apress"),
  array("ID"=>44749,"Area"=>"Zone 3","Subarea"=>"ASUS"),
  array("ID"=>44496,"Area"=>"Zone 3","Subarea"=>"Atmel"),
  array("ID"=>43743,"Area"=>"Zone 3","Subarea"=>"Autodesk"),
  array("ID"=>44501,"Area"=>"Zone 3","Subarea"=>"Beagleboard"),
  array("ID"=>44510,"Area"=>"Zone 4","Subarea"=>"Boots Industries"),
  array("ID"=>44502,"Area"=>"Zone 2","Subarea"=>"BuildTak"),
  array("ID"=>43431,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45362,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45363,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45364,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45365,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45366,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45367,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45368,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45369,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45370,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45371,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45372,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45373,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45374,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45375,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45376,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45377,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45378,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45379,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45380,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45381,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45382,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45383,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45384,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45385,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45386,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45387,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45388,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45389,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45390,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45391,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45392,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45393,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45394,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45395,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45396,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45397,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45398,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45399,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45400,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45401,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45402,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45403,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45404,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45405,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45406,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45407,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45408,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45409,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45410,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45411,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45413,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45414,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45415,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45416,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45417,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45418,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45419,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45420,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45421,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45422,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45423,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45424,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45425,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45426,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45427,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45428,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45429,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45430,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45431,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45432,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45433,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45434,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45435,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45436,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45437,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45438,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45439,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45440,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45441,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>45487,"Area"=>"Zone 2","Subarea"=>"BUST Craftacular"),
  array("ID"=>43744,"Area"=>"Zone 4","Subarea"=>"Carbide Labs"),
  array("ID"=>43745,"Area"=>"Zone 4","Subarea"=>"Carbon Origins"),
  array("ID"=>34956,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>34964,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>35149,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>35650,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>35798,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>36046,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>36352,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>36470,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>36620,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>37061,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>37204,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>37277,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>37296,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>37484,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>37671,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>37707,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>37767,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>37839,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>37891,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>37900,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>38092,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>38277,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>38344,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>38369,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>38375,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>38515,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>38617,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>38728,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>38836,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>38958,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>39007,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>39183,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>39990,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>40234,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>40281,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>40322,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>40406,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>40470,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>40933,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>40952,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>41717,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>42332,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>45448,"Area"=>"Zone 2","Subarea"=>"Center"),
  array("ID"=>34974,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>35010,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>35540,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>35710,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>35820,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>35841,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>35864,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>36477,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>36559,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>36832,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>36920,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>36951,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>36990,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>37120,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>37268,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>37279,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>37399,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>37408,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>37469,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>37931,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>38042,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>38089,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>38167,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>38328,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>38540,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>38575,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>38877,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>38965,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>39083,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>39229,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>39544,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>39607,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>39785,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>39900,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>39962,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>40496,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>40563,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>40595,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>40814,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>41212,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>42577,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>43711,"Area"=>"Zone 3","Subarea"=>"Center Green"),
  array("ID"=>45494,"Area"=>"Zone 4","Subarea"=>"Circus Warehouse"),
  array("ID"=>43746,"Area"=>"Zone 3","Subarea"=>"Cognizant"),
  array("ID"=>43882,"Area"=>"Zone 3","Subarea"=>"Cognizant"),
  array("ID"=>42592,"Area"=>"Zone 4","Subarea"=>"Coke Zero & Mentos Stage"),
  array("ID"=>44517,"Area"=>"Zone 3","Subarea"=>"Cornell"),
  array("ID"=>44771,"Area"=>"Zone 4","Subarea"=>"Creative Electron"),
  array("ID"=>43749,"Area"=>"Zone 3","Subarea"=>"Delta Faucet"),
  array("ID"=>44503,"Area"=>"Zone 3","Subarea"=>"DFRobot"),
  array("ID"=>44504,"Area"=>"Zone 3","Subarea"=>"Digi"),
  array("ID"=>43750,"Area"=>"Zone 3","Subarea"=>"Dremel"),
  array("ID"=>35029,"Area"=>"Zone 4","Subarea"=>"Drone Zone"),
  array("ID"=>35117,"Area"=>"Zone 4","Subarea"=>"Drone Zone"),
  array("ID"=>36702,"Area"=>"Zone 4","Subarea"=>"Drone Zone"),
  array("ID"=>37812,"Area"=>"Zone 4","Subarea"=>"Drone Zone"),
  array("ID"=>38405,"Area"=>"Zone 4","Subarea"=>"Drone Zone"),
  array("ID"=>38485,"Area"=>"Zone 4","Subarea"=>"Drone Zone"),
  array("ID"=>40579,"Area"=>"Zone 4","Subarea"=>"Drone Zone"),
  array("ID"=>42384,"Area"=>"Zone 4","Subarea"=>"Drone Zone"),
  array("ID"=>43123,"Area"=>"Zone 4","Subarea"=>"Drone Zone"),
  array("ID"=>43838,"Area"=>"Zone 4","Subarea"=>"Drone Zone"),
  array("ID"=>35577,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>36171,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>36391,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>36901,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>37154,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>37310,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>37342,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>37487,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>37761,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>38153,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>38262,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>38341,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>38487,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>38498,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>38549,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>38570,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>38633,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>39490,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>39774,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>39858,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>40054,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>40514,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>41751,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>43747,"Area"=>"Zone 3","Subarea"=>"Electronics Pavilion"),
  array("ID"=>43751,"Area"=>"Zone 4","Subarea"=>"Electroninks Writeables"),
  array("ID"=>43752,"Area"=>"Zone 3","Subarea"=>"Epilog Laser"),
  array("ID"=>44505,"Area"=>"Zone 3","Subarea"=>"First Build"),
  array("ID"=>37126,"Area"=>"Zone 4","Subarea"=>"Fly Zone"),
  array("ID"=>38922,"Area"=>"Zone 4","Subarea"=>"Fly Zone"),
  array("ID"=>38927,"Area"=>"Zone 4","Subarea"=>"Fly Zone"),
  array("ID"=>40966,"Area"=>"Zone 4","Subarea"=>"Fly Zone"),
  array("ID"=>43753,"Area"=>"Zone 4","Subarea"=>"Ford"),
  array("ID"=>43754,"Area"=>"Zone 2","Subarea"=>"Formlabs"),
  array("ID"=>43755,"Area"=>"Zone 3","Subarea"=>"Freescale Inc."),
  array("ID"=>37010,"Area"=>"Zone 4","Subarea"=>"Game of Drones"),
  array("ID"=>34921,"Area"=>"Zone 2","Subarea"=>"Green"),
  array("ID"=>35804,"Area"=>"Zone 2","Subarea"=>"Green"),
  array("ID"=>36398,"Area"=>"Zone 2","Subarea"=>"Green"),
  array("ID"=>38053,"Area"=>"Zone 2","Subarea"=>"Green"),
  array("ID"=>38589,"Area"=>"Zone 2","Subarea"=>"Green"),
  array("ID"=>38690,"Area"=>"Zone 2","Subarea"=>"Green"),
  array("ID"=>40333,"Area"=>"Zone 2","Subarea"=>"Green"),
  array("ID"=>40335,"Area"=>"Zone 2","Subarea"=>"Green"),
  array("ID"=>40599,"Area"=>"Zone 3","Subarea"=>"Green Annex"),
  array("ID"=>42146,"Area"=>"Zone 3","Subarea"=>"Green Annex"),
  array("ID"=>36650,"Area"=>"Zone 3","Subarea"=>"Habitat for Humanity"),
  array("ID"=>36110,"Area"=>"Zone 5","Subarea"=>"Health"),
  array("ID"=>37106,"Area"=>"Zone 5","Subarea"=>"Health"),
  array("ID"=>42226,"Area"=>"Zone 5","Subarea"=>"Health"),
  array("ID"=>42246,"Area"=>"Zone 5","Subarea"=>"Health"),
  array("ID"=>43756,"Area"=>"Zone 2","Subarea"=>"iMaterialise"),
  array("ID"=>35018,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>35104,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>35260,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>35282,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>35285,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>35419,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>35475,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>35559,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>35740,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>35937,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>36039,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>36100,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>36544,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>36599,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>36743,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>36846,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37063,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37134,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37179,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37243,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37349,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37427,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37437,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37503,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37509,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37527,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37549,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37624,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37643,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37750,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>37800,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>38108,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>38213,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>38224,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>38244,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>38410,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>38643,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>38656,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>38694,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>38744,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>38816,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>39719,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>39971,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>40059,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>40112,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>40247,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>40300,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>40796,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>40964,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>41046,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>41252,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>41625,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>41814,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>42093,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>43064,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>43117,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>44802,"Area"=>"Zone 1","Subarea"=>"Inside NYSCI"),
  array("ID"=>43757,"Area"=>"Zone 3","Subarea"=>"Intel"),
  array("ID"=>43758,"Area"=>"Zone 3","Subarea"=>"Italian Trade Agency"),
  array("ID"=>41617,"Area"=>"Zone 5","Subarea"=>"ITP Orchestra"),
  array("ID"=>35879,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>36405,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>37579,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>37664,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>38523,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>41331,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>41767,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>41801,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>41826,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>42010,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>42036,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>42061,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>42105,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>42110,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>42552,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>43215,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>43425,"Area"=>"Zone 2","Subarea"=>"Kickstarter"),
  array("ID"=>43271,"Area"=>"Zone 3","Subarea"=>"Learn to Solder Activity powered by RadioShack"),
  array("ID"=>43760,"Area"=>"Zone 3","Subarea"=>"LEGO MINDSTORMS"),
  array("ID"=>44495,"Area"=>"Zone 3","Subarea"=>"LG"),
  array("ID"=>40750,"Area"=>"Zone 4","Subarea"=>"Life-Size Mousetrap"),
  array("ID"=>42598,"Area"=>"Zone 4","Subarea"=>"Life-Size Mousetrap"),
  array("ID"=>43761,"Area"=>"Zone 3","Subarea"=>"Linino / CC Logistics"),
  array("ID"=>44514,"Area"=>"Zone 3","Subarea"=>"LINUX"),
  array("ID"=>43762,"Area"=>"Zone 3","Subarea"=>"LIQUID WRENCH"),
  array("ID"=>43763,"Area"=>"Zone 3","Subarea"=>"littleBits"),
  array("ID"=>40878,"Area"=>"Zone 4","Subarea"=>"Lockpick Village - Presented by TOOOL"),
  array("ID"=>43764,"Area"=>"Zone 4","Subarea"=>"MadeSolid"),
  array("ID"=>41771,"Area"=>"Zone 3","Subarea"=>"Make"),
  array("ID"=>43287,"Area"=>"Zone 3","Subarea"=>"Make"),
  array("ID"=>43465,"Area"=>"Zone 3","Subarea"=>"Make"),
  array("ID"=>43569,"Area"=>"Zone 3","Subarea"=>"Make"),
  array("ID"=>35144,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>35407,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>35770,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>36010,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>36053,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>36130,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>36367,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>36462,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>36931,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>37094,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>37222,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>37439,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>37534,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>37877,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>37911,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>37985,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38003,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38085,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38115,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38319,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38338,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38358,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38386,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38422,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38449,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38560,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38603,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38852,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38855,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38872,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>38989,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>39757,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>39790,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>40317,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>40747,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>40799,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>40876,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>40893,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>41193,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>41860,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>42316,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>42478,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>42709,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>43672,"Area"=>"Zone 3","Subarea"=>"Maker Pavilion"),
  array("ID"=>44255,"Area"=>"Zone 2","Subarea"=>"Maker Pavilion"),
  array("ID"=>35611,"Area"=>"Zone 4","Subarea"=>"Maker Shed"),
  array("ID"=>36122,"Area"=>"Zone 4","Subarea"=>"Maker Shed"),
  array("ID"=>37521,"Area"=>"Zone 4","Subarea"=>"Maker Shed"),
  array("ID"=>38650,"Area"=>"Zone 4","Subarea"=>"Maker Shed"),
  array("ID"=>39146,"Area"=>"Zone 4","Subarea"=>"Maker Shed"),
  array("ID"=>42348,"Area"=>"Zone 4","Subarea"=>"Maker Shed"),
  array("ID"=>43243,"Area"=>"Zone 4","Subarea"=>"Maker Shed"),
  array("ID"=>43299,"Area"=>"Zone 4","Subarea"=>"Maker Shed"),
  array("ID"=>43537,"Area"=>"Zone 4","Subarea"=>"Maker Shed"),
  array("ID"=>44289,"Area"=>"Zone 4","Subarea"=>"Maker Shed"),
  array("ID"=>43766,"Area"=>"Zone 2","Subarea"=>"MakerBot"),
  array("ID"=>43765,"Area"=>"Zone 3","Subarea"=>"MathWorks"),
  array("ID"=>43767,"Area"=>"Zone 3","Subarea"=>"McGraw-Hill Education"),
  array("ID"=>43768,"Area"=>"Zone 3","Subarea"=>"Meccano (Spin Master)"),
  array("ID"=>43769,"Area"=>"Zone 4","Subarea"=>"Metasphere"),
  array("ID"=>43770,"Area"=>"Zone 3","Subarea"=>"Micro Center"),
  array("ID"=>44498,"Area"=>"Zone 3","Subarea"=>"Microsoft"),
  array("ID"=>43771,"Area"=>"Zone 4","Subarea"=>"Mighty Mug"),
  array("ID"=>35126,"Area"=>"Zone 3","Subarea"=>"Mobile"),
  array("ID"=>35749,"Area"=>"Zone 3","Subarea"=>"Mobile"),
  array("ID"=>36438,"Area"=>"Zone 3","Subarea"=>"Mobile"),
  array("ID"=>38495,"Area"=>"Zone 3","Subarea"=>"Mobile"),
  array("ID"=>39576,"Area"=>"Zone 3","Subarea"=>"Mobile"),
  array("ID"=>38036,"Area"=>"Zone 5","Subarea"=>"MoMath"),
  array("ID"=>37835,"Area"=>"Zone 3","Subarea"=>"Mozilla Webmaker"),
  array("ID"=>43772,"Area"=>"Zone 3","Subarea"=>"Mozilla Webmaker"),
  array("ID"=>43773,"Area"=>"Zone 3","Subarea"=>"NASA"),
  array("ID"=>38760,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42780,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42789,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42794,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42811,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42824,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42829,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42834,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42843,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42850,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42855,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42860,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42865,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42933,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42938,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42943,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>42948,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>43031,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>44243,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>44250,"Area"=>"Zone 1","Subarea"=>"NYSCI Village"),
  array("ID"=>43774,"Area"=>"Zone 3","Subarea"=>"OGOSPORT LLC"),
  array("ID"=>44494,"Area"=>"Zone 4","Subarea"=>"PepsiCo"),
  array("ID"=>44513,"Area"=>"Zone 4","Subarea"=>"Play-i"),
  array("ID"=>35002,"Area"=>"Zone 2","Subarea"=>"Power Racing Series Race Track"),
  array("ID"=>36451,"Area"=>"Zone 2","Subarea"=>"Power Racing Series Race Track"),
  array("ID"=>38076,"Area"=>"Zone 2","Subarea"=>"Power Racing Series Race Track"),
  array("ID"=>38346,"Area"=>"Zone 2","Subarea"=>"Power Racing Series Race Track"),
  array("ID"=>38536,"Area"=>"Zone 2","Subarea"=>"Power Racing Series Race Track"),
  array("ID"=>38615,"Area"=>"Zone 2","Subarea"=>"Power Racing Series Race Track"),
  array("ID"=>38879,"Area"=>"Zone 2","Subarea"=>"Power Racing Series Race Track"),
  array("ID"=>41021,"Area"=>"Zone 2","Subarea"=>"Power Racing Series Race Track"),
  array("ID"=>43788,"Area"=>"Zone 2","Subarea"=>"PP3DP/UP!/Tiertime"),
  array("ID"=>37217,"Area"=>"Zone 5","Subarea"=>"Puppet Phactory's Hack-A-Puppet"),
  array("ID"=>44788,"Area"=>"Zone 3","Subarea"=>"RadioShack"),
  array("ID"=>43776,"Area"=>"Zone 3","Subarea"=>"ROBLOX"),
  array("ID"=>34992,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>35685,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>35898,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>36197,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>36567,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>37024,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>38464,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>39031,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>39046,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>39188,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>39467,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>40440,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>40843,"Area"=>"Zone 3","Subarea"=>"Robot Row"),
  array("ID"=>43619,"Area"=>"Zone 4","Subarea"=>"Rocket Roundabout"),
  array("ID"=>36027,"Area"=>"Zone 1","Subarea"=>"Rotunda"),
  array("ID"=>35398,"Area"=>"Zone 5","Subarea"=>"Roundabout"),
  array("ID"=>39071,"Area"=>"Zone 5","Subarea"=>"Roundabout"),
  array("ID"=>40117,"Area"=>"Zone 5","Subarea"=>"Roundabout"),
  array("ID"=>42085,"Area"=>"Zone 5","Subarea"=>"Roundabout"),
  array("ID"=>36266,"Area"=>"Zone 4","Subarea"=>"Science Avenue"),
  array("ID"=>44010,"Area"=>"Zone 4","Subarea"=>"Science Avenue"),
  array("ID"=>35037,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>35919,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>36622,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>36689,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>36715,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>37458,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>37532,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>37676,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>37994,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>38227,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>38249,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>38256,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>38503,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>38654,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>40636,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>40757,"Area"=>"Zone 5","Subarea"=>"Science Playground"),
  array("ID"=>43778,"Area"=>"Zone 1","Subarea"=>"SeeMeCNC"),
  array("ID"=>43779,"Area"=>"Zone 2","Subarea"=>"Shapeways"),
  array("ID"=>43780,"Area"=>"Zone 2","Subarea"=>"Shenzhen Esun Industrial Co.,Ltd"),
  array("ID"=>43781,"Area"=>"Zone 3","Subarea"=>"ShopBot Tools"),
  array("ID"=>43782,"Area"=>"Zone 4","Subarea"=>"Simplify3D Software"),
  array("ID"=>37732,"Area"=>"Zone 5","Subarea"=>"Skatehack"),
  array("ID"=>43783,"Area"=>"Zone 2","Subarea"=>"SketchUp "),
  array("ID"=>43784,"Area"=>"Zone 4","Subarea"=>"SmartJars "),
  array("ID"=>44511,"Area"=>"Zone 4","Subarea"=>"Solidoodle"),
  array("ID"=>43775,"Area"=>"Zone 3","Subarea"=>"Sphero"),
  array("ID"=>43785,"Area"=>"Zone 4","Subarea"=>"Structur3D Printing"),
  array("ID"=>44507,"Area"=>"Zone 3","Subarea"=>"Sugru"),
  array("ID"=>35364,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>36652,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>36671,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>36800,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>37476,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>38176,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>38553,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>38635,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>38698,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>40710,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>41309,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>41600,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>42067,"Area"=>"Zone 5","Subarea"=>"Sustainability"),
  array("ID"=>43786,"Area"=>"Zone 3","Subarea"=>"Texas Instruments"),
  array("ID"=>43787,"Area"=>"Zone 4","Subarea"=>"The Creativity Hub"),
  array("ID"=>42079,"Area"=>"Zone 3","Subarea"=>"The Grommet"),
  array("ID"=>44744,"Area"=>"Zone 3","Subarea"=>"The Walt Disney Company"),
  array("ID"=>44515,"Area"=>"Zone 4","Subarea"=>"Time Warner Cable"),
  array("ID"=>44509,"Area"=>"Zone 4","Subarea"=>"Tinkerine"),
  array("ID"=>44493,"Area"=>"Zone 2","Subarea"=>"Toyota"),
  array("ID"=>44795,"Area"=>"Zone 1","Subarea"=>"Turner TV"),
  array("ID"=>43789,"Area"=>"Zone 1","Subarea"=>"Uber"),
  array("ID"=>44506,"Area"=>"Zone 3","Subarea"=>"Udoo"),
  array("ID"=>43790,"Area"=>"Zone 2","Subarea"=>"Ultimaker"),
  array("ID"=>43791,"Area"=>"Zone 3","Subarea"=>"Velleman Inc."),
  array("ID"=>43793,"Area"=>"Zone 3","Subarea"=>"Vex Robotics"),
  array("ID"=>35042,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>35133,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>35151,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>35339,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>35451,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>35675,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>35914,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>35956,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>35961,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>36095,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>36225,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>36291,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>36753,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>36915,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>37041,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>37576,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>38058,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>38456,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>38565,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>38572,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>38735,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>39482,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>39935,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>40009,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>40994,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>42042,"Area"=>"Zone 1","Subarea"=>"Viscuzi Gallery"),
  array("ID"=>43792,"Area"=>"Zone 3","Subarea"=>"Wiley"),
  array("ID"=>43794,"Area"=>"Zone 2","Subarea"=>"XYZ Printing"),
  array("ID"=>35136,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>35274,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>35344,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>35551,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>36204,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>36709,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>36755,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>36856,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>36979,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>37567,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>37712,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>37726,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>37755,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>37825,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>37856,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>37949,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>38938,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>38954,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>38972,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>38999,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>39597,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>40364,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>40708,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>40907,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>41650,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>42305,"Area"=>"Zone 3","Subarea"=>"Young Makers"),
  array("ID"=>35160,"Area"=>"Zone 3","Subarea"=>""),
  array("ID"=>35263,"Area"=>"Zone 3","Subarea"=>""),
  array("ID"=>35734,"Area"=>"Zone 3","Subarea"=>""),
  array("ID"=>36938,"Area"=>"Zone 4","Subarea"=>""),
  array("ID"=>37419,"Area"=>"Zone 3","Subarea"=>""),
  array("ID"=>37695,"Area"=>"Zone 3","Subarea"=>""),
  array("ID"=>37739,"Area"=>"Zone 3","Subarea"=>""),
  array("ID"=>38834,"Area"=>"Zone 3","Subarea"=>""),
  array("ID"=>39020,"Area"=>"Zone 5","Subarea"=>""),
  array("ID"=>40419,"Area"=>"Zone 3","Subarea"=>""),
  array("ID"=>40453,"Area"=>"Zone 3","Subarea"=>""),
  array("ID"=>40669,"Area"=>"Zone 3","Subarea"=>""),
  array("ID"=>40678,"Area"=>"Zone 3","Subarea"=>"")
);